defaults:
  - base
  - _self_

train:
  use_sfttrainer: false
  optimizer_param_groups:
    - params_regex: ".*vision_tower.*"
      lr_multiplier: 0.9
    - params_regex: ".*multi_modal_projector.*"
      lr_multiplier: 0.9
    - params_regex: ".*language_model.*"
      lr_multiplier: 1.0